title: Just the Docs
description: A Jekyll theme for documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://notes.andykee.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: andykee/notes # for github-metadata
