name: Build and publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_REGION : us-west-2
  S3_BUCKET: ak-dump
  
permissions:
  id-token: write   
  contents: read   
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: pip install -r ${{ github.workspace }}/.github/pelican/requirements.txt
        
      - name: Build
        run: mkdir ${{ github.workspace }}/output
        run: python ${{ github.workspace }}/.github/pelican/build.py ${{ github.workspace }} ${{ github.workspace }}/output


      - run: ls
      - run: ls output


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::826183391955:role/github_actions
          role-session-name: publish
          aws-region: ${{ env.AWS_REGION }}
  
      #- name: Upload to S3
      #  working-directory: ${{ env.applicationfolder }}
      #  run: aws s3 sync _site/ s3://${{ env.S3_BUCKET }}
